name = "compass"
license = "MPL-2.0"
licenselink = "https://github.com/xorkevin/compass/blob/master/LICENSE"
description = "a hugo theme for project hosting"
homepage = "http://github.com/xorkevin/compass"
tags = []
features = []
min_version = "0.55"

[author]
  name = "Kevin Wang"
  homepage = "xorkevin.com"
